using System;
using System.Collections.Generic;
using System.Drawing;
using MoonSharp.Interpreter;
using MoonSharp.Interpreter.Interop;
using Quaver.API.Helpers;

namespace Quaver.API.Maps.Structures
{
    [Serializable]
    [MoonSharpUserData]
    public class EditorLayerInfo
    {
        /// <summary>
        ///     The name of the layer
        /// </summary>
        public string Name { get; [MoonSharpVisible(false)] set; }

        /// <summary>
        ///     Is the layer hidden in the editor?
        /// </summary>
        public bool Hidden { get; [MoonSharpVisible(false)] set; }

        /// <summary>
        ///     The color of the layer (default is white)
        /// </summary>
        public string ColorRgb { get; [MoonSharpVisible(false)] set; }

        /// <summary>
        ///     Converts the stringified color to a System.Drawing color
        /// </summary>
        /// <returns></returns>
        [MoonSharpVisible(false)]
        public Color GetColor() =>
            new Drain<char>(ColorRgb, ',') is var (tr, (tg, (tb, _))) &&
            byte.TryParse(tr, out var r) &&
            byte.TryParse(tg, out var g) &&
            byte.TryParse(tb, out var b)
                ? Color.FromArgb(r, g, b)
                : Color.White;

        /// <summary>
        ///     By-value comparer, auto-generated by Rider.
        /// </summary>
        private sealed class ByValueEqualityComparer : IEqualityComparer<EditorLayerInfo>
        {
            public bool Equals(EditorLayerInfo x, EditorLayerInfo y)
            {
                if (ReferenceEquals(x, y)) return true;
                if (ReferenceEquals(x, null)) return false;
                if (ReferenceEquals(y, null)) return false;
                if (x.GetType() != y.GetType()) return false;
                return string.Equals(x.Name, y.Name) && x.Hidden == y.Hidden && string.Equals(x.ColorRgb, y.ColorRgb);
            }

            public int GetHashCode(EditorLayerInfo obj)
            {
                unchecked
                {
                    var hashCode = obj.Name.GetHashCode();
                    hashCode = (hashCode * 397) ^ obj.Hidden.GetHashCode();
                    hashCode = (hashCode * 397) ^ obj.ColorRgb.GetHashCode();
                    return hashCode;
                }
            }
        }

        public static IEqualityComparer<EditorLayerInfo> ByValueComparer { get; } = new ByValueEqualityComparer();
    }
}
